export type ActivityEventItem = {
  sequence_no: number;       // auto generated by db, used by workers to track progress. Primary key for the table.
  event_id: string;       
  event_occurred_at: Date; 
  event_domain: string;
  event_type: string;
  aggregate_type: string;
  aggregate_id: string;
  event_payload_json: string;
  //schema_version: number; // the version of the schema used to create the event
  //created_at: Date;       // the time the event was created in the database
};

