
/**
 *    output model for release feed
 *    By exposing release feed API, in addtion to feeds api, we can expose here release specific data
 *    so the API is clear and docused on what's new screen.
 */
export interface ReleaseFeedOutput {
  items: ReleaseFeedItem[];
  cursor?: string;  // Generated by service. client should send this value in the next page request  to support paging 
                    // using crursor+limit instead offset+limit since events keeps coming in
                    // using string in the api hides the internal details of the cursor from the client
                    // for now the cursor is encoded as base64url of JSON { releaseDate, releasedObjectId } 
                    // (usually it is event time + event id but this time we dont have event id since we dont have events\feeds table yet)
}

export interface ReleaseFeedItem {
  /** Who performed the action (artists releasing same album or shows adding episodes). */
  feedActors: ReleaseFeedActor[];
  /** The action performed (e.g. "released"). */
  feedVerb: "released";
  /** The thing that was updated | created | deleted (album or episode).
   *  This is unified release api. Released object is either album or episode.
   */
  feedObject: ReleaseFeedObject;
  /** When the release happened (ISO 8601 datetime). */
  occurredAt: string;
}


export interface ReleaseFeedActor {
  type: "artist" | "show";
  id: string;
  name: string;
}

/**
 * Polymorphic object: album or episode.
 * Optional fields (episodeDurationMs, albumType) are nullable depending on type.
 * Using a single unified shape instead of separate album/episode types keeps the API simple;
 * this is reasonable since there are few such type-specific fields.
 */
export interface ReleaseFeedObject {
  type: "album" | "episode";
  id: string;
  title: string;
  imageUrl: string;
  /** Present when type === "episode"; absent otherwise. */
  episodeDurationMs?: number;
  /** Present when type === "album"; absent otherwise. */
  albumType?: ReleaseFeedAlbumType;
}



/** Album type: album, single, or compilation. */
export type ReleaseFeedAlbumType = "album" | "single" | "compilation";




