import type { MySqlConnection } from "@mycompanyname/lib-common";
import * as activityEventsRepository from "../../../infrastructure/activity-events/activity-events.repository";

const infrastructure = {
  activityEvents: activityEventsRepository,
};

import { DOMAIN_CATALOG, ActorTypes, EventTypes, AggregateTypes } from "./types/activity-events.constants";
import type { AlbumReleasedEventPayload } from "./types/activity-events.payloads";



/**
 * 
/**
 * Catalog adapter for writing catalog-owned domain events into the shared
 * `activity_events` storage.
 *
 * Current usage (Modular Monolith with projection workers):
 * - Catalog write services update catalog source-of-truth tables
 *   (e.g. updating `albums.released_at`).
 * - In the same transaction, they call this service to append a corresponding
 *   activity event into the shared activity log.
 * - Reader domains (feeds, analytics, search, notifications) run workers that
 *   consume these events incrementally and build their own projection tables.
 * - Reader APIs query those projection tables instead of the catalog tables.
 *
 *
 * Responsibilities of this service
 * --------------------------------
 * This service acts as a **catalog-specific adapter** between catalog domain
 * events and the shared activity-events infrastructure.
 *
 * It is responsible for:
 * - receiving a catalog event payload
 * - mapping it into the `activity_events` envelope structure
 * - mapping related actors into `activity_event_actors`
 * - calling the infrastructure repository to persist both
 *
 * Business logic (album rules, validations, etc.) stays in catalog domain
 * services such as `albumService`. This service contains only the mapping
 * from catalog domain events to the shared activity-event storage format.
 *
 *
 * Transaction participation
 * -------------------------
 * The `conn` parameter is passed so this operation can participate in the
 * caller's transaction.
 *
 * Typical flow:
 *
 *   1. catalog service updates domain tables (e.g. `albums.released_at`)
 *   2. catalog service calls this method
 *   3. this method writes to:
 *        - `activity_events`
 *        - `activity_event_actors`
 *   4. the transaction commits atomically
 *
 * This guarantees that the domain change and the emitted event remain consistent.
 *
 *
 * Why the caller provides `eventId`
 * ---------------------------------
 * The caller generates the `eventId` and passes it to this service instead of
 * letting the repository generate it internally.
 *
 * This is intentional and provides several architectural benefits:
 *
 * 1. **Future compatibility with message-based architectures**
 *
 *    In later versions of the system we may move from the current
 *    "activity_events + workers" model to a message broker (Kafka, SQS,
 *    RabbitMQ, etc.).
 *
 *    In that model the producer domain publishes an event message like:
 *
 *      {
 *        eventId: "uuid",
 *        eventType: "catalog.album_released",
 *        eventTime: "...",
 *        eventPayload: {...}
 *      }
 *
 *    Because the event ID already originates in the producer domain,
 *    the same ID can be reused consistently across:
 *
 *      - the message
 *      - the activity_events table
 *      - downstream projection tables
 *
 *
 * 2. **Idempotency and deduplication**
 *
 *    Consumers (workers or message consumers) can use `eventId` to detect
 *    duplicate deliveries or retries.
 *
 *    This becomes especially important in distributed systems where events
 *    may be delivered more than once.
 *
 *
 * 3. **Tracing and observability**
 *
 *    Having a stable event ID generated by the producer domain allows easier
 *    tracing across logs, services, queues, and projection workers.
 *
 *
 * 4. **Replay and migration safety**
 *
 *    If events are later replayed (for rebuilding projections or migrating
 *    systems), the same `eventId` remains stable and can be used to ensure
 *    deterministic processing.
 *
 *
 * Payload design
 * --------------
 * Event payloads intentionally contain enough data for reader domains to build
 * their projections without querying the producer domain tables.
 *
 * This avoids:
 * - cross-domain database joins in the monolith
 * - synchronous REST calls between services in a microservices architecture
 *
 * Instead, reader domains process the event payload and update their own
 * projection tables independently.
 */
 
/**
 * This service acts as adapeter that gets the **catalog** events and writes them into storage
 * (Usage: release album v4 - monolith with workers building projection tables)
 * 
 * This service is an adapter for **catalog** domain events, writing them into storage 
 * Usage: release album v4 - reader domain, eg feeds/search/analytics, run workers that reads the events from staorage and write to projection tables
 *                           the reader API reads the projection tables and returns the data to the reader domain
 * 
 * Flow:
 * 1. (album) service updates the domain table (`album`).
 * 2. (album) service calls this service to write the event into storage.
 * 3. This service receives the event payload.
 * 4. This service maps the event payload into `activity_events` + `activity_event_actors` rows.
 * 5. This service calls the infrastructure repository to persist the activity event.
 *
 * 
 * Design notes:
 * 
 * 1. seperation of concerns
 *    domain service (`albumService`) stays focused on album business rules
 *    this service owns mapping logic (from event payload to activity-events and activity-event-actors) 
 *    infrastructure service (activity-events)  owns writing events into the shared activity log tables.
 *
 
 * 2. The `conn` parameter
       is passed in so this method can participate in the
 *    caller's transaction. For example, inserting into `activity_events` and
 *    `activity_event_actors` and updating album.released_atshould usually happen atomically.
 *
 * 
 * 3. The `eventId` parameter
 *    - For the current version, either design could work:
 *      - Option 1: generate `eventId` inside this method
 *      - Option 2: receive `eventId` from the caller
 *      - We choose option 2because we can reuse the same api later when we move from activitiy event + workers to message queues.
 *
 *    In this version, 
 *    the writer domain (album-released)
 *         write to the writer domain (album table)
 *         and calls activityEventService to write to activityEvents domain
 *    Later on, when we move to message queues, the writer domain (album-released) will
 *         write to the writer domain table as before
 *         but will also publish the event (with event id) to the queue.
 *         The example future event message:
 *        {
 *          eventId: "123", ***** getting event id as input*****
 *          eventType: "album_released",
 *          eventTime: "2026-03-15T10:00:00Z",
 *          eventPayload: { album: { id: "123", name: "Album 1" } }
 *        }
 * 
 *        Each reader domain (analytics, feeds, notifications, etc.)
 *         can then have its own consumer that reads the message (eg, in bulks)
 *         and writes to its own projection tables
 *        (eg, analytics module reading te messages and writing to stat projection tables
 *         eg, feeds module reading the messages and writing to feed projection tables
 *         eg, activity events module reading the messages and writing to activity events tables
 *         eg, search module reading the messages and writing to search_index tables
 * 
 *         In that model, the published event message will already contain `eventId`,
 *         and consumers can use it for idempotency, deduplication, tracing, or replay.
 * 
 * 
 * 4. Envelope fields such as `aggregateId` and `eventTime` are derived from
 *    the payload (`payload.album.id`, `payload.releasedAt`) because this method
 *    is already coupled to `AlbumReleasedEventPayload`.
 * 
 * 5. By having the payload object  enriched with data , we ensure that the workers from reader domain will not have to call the writter domain (rest api in ms) to read data
 */
 
export async function insertAlbumReleaseActivityEvent(
  conn: MySqlConnection,
  eventId: string,
  payload: AlbumReleasedEventPayload
): Promise<void> {
  await infrastructure.activityEvents.insertActivityEvent(conn, {
    eventId,
    eventOccurredAt: payload.releasedAt,
    eventDomain: DOMAIN_CATALOG,
    eventType: EventTypes.ALBUM_RELEASED,
    aggregateType: AggregateTypes.ALBUM,
    aggregateId: payload.album.id,
    eventPayload: payload,
    schemaVersion: 1,
  });

  await infrastructure.activityEvents.insertActivityEventActors(conn, {
    eventId,
    actors: payload.artists.map((artist) => ({
      actorType: ActorTypes.ARTIST,
      actorId: artist.id,
      actorName: artist.name,
    })),
  });
}

