/**
 * Phase 10.7
 * File module exporting Express middleware for request context initialization
 * 
 * Goal:
 *    Initialize framework-agnostic request context and set correlationId
 *    CorrelationId enables log aggregation across microservices for a single request
 * 
 * Architecture:
 *    - Framework-dependent: Express-specific middleware
 *    - Business code remains framework-agnostic (uses requestContext utility)
 *    - Context is accessible from ANY layer: controllers, services, repositories, logger, etc.
 *    - CorrelationId is stored in framework-agnostic requestContext, not on req object
 * 
 * Flow:
 *    1. Reads x-correlation-id from request header (if present)
 *    2. Generates new UUID if header is missing
 *    3. Initializes request context using withRequestContext()
 *    4. Stores correlationId in request context (accessible via requestContext.getCorrelationId())
 *    5. Sets correlationId in response header (x-correlation-id) for client/microservice propagation
 *    6. Continues request processing within the context scope
 * 
 * Usage:
 *    - app applies requestContextMiddleware as first middleware
 *      app.use(requestContextMiddleware);
 *    - any layer (app controllers domain, infra, utils) can
 *      read correlationId using requestContext.getCorrelationId()
 * 
 * Dependencies:
 *    cd in serverWorkspace/packages/lib-common
 *    npm install express
 * 
 * Notes:
 *    - CorrelationId should be generated by the first microservice (e.g., API Gateway or auth service)
 *    - Subsequent microservices should read it from header and pass it along
 *    - Logger automatically includes correlationId in logs without explicit passing
 */
import { Request, Response, NextFunction } from 'express';
import { requestContext, withRequestContext } from "../../utils/request-context";

import { randomUUID } from 'node:crypto';
const CORRELATION_ID_HEADER = 'x-correlation-id';

export function requestContextMiddleware(req: Request, res: Response, next: NextFunction) {
  // 1. Read correlation id from request headers, Convert headerValue to string | undefined (handle array case)
  const headerValue: string | string[] = req.headers[CORRELATION_ID_HEADER] || req.headers[CORRELATION_ID_HEADER.toLowerCase()];
  const incomingCorrelationId: string | undefined = 
    headerValue ? (Array.isArray(headerValue) ? headerValue[0] : headerValue) : undefined;
  
  // 2. Generate new UUID if header is missing
  const correlationId: string = incomingCorrelationId || randomUUID();
  
  // 3. Initialize request context and process request within context scope
  withRequestContext(() => {
    // 3.1 Store correlation id in request context (used by logger, services, controllers)
    //     Accessible via requestContext.getCorrelationId() from any layer
    requestContext.setCorrelationId(correlationId);
    // 3.2 Store correlation id in response header for client/microservice propagation
    res.setHeader(CORRELATION_ID_HEADER, correlationId);
    // 3.3 Continue request processing within the context scope
    next();
  });
}
