import { logger, mysqlPool, type MySqlConnection } from "@mycompanyname/lib-common";
import type { AddActivityEventInput } from "./types/add.activity.event.input.model";
import type { AddActivityEventActorsInput } from "./types/add.activity.event.actors.input.model";
import type { ActivityEventItem } from "./types/activityEvent.item.model";
import type { ActivityEventActorItem } from "./types/activityEventActor.item.model";

const LOG_SCOPE = "activityEvents.repository";




/**
 * Inserts a single event row into `activity_events`.
 *
 * Notes:
 * - This repository layer is generic and does not depend on a specific event type
 *   (album released, episode released, etc.).
 * - This method can be executed inside an existing transaction because it receives
 *   the DB connection as a parameter.
 * - `sequence_no` is generated by the database and used by workers for checkpointing.
 * - `created_at` is generated by the database.
 * - Does not write to `activity_event_actors`; callers handle that separately.
 */
export async function insertActivityEvent<TEventPayload>(
  conn: MySqlConnection,
  event: AddActivityEventInput<TEventPayload>
): Promise<void> {
  const payloadJson = JSON.stringify(event.eventPayload ?? null);
  const sqlEvent = `
    INSERT INTO activity_events (
      event_id,
      event_occurred_at,
      event_domain,
      event_type,
      aggregate_type,
      aggregate_id,
      event_payload_json,
      schema_version
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `;
  const paramsEvent = [
    event.eventId,
    event.eventOccurredAt,
    event.eventDomain,
    event.eventType,
    event.aggregateType,
    event.aggregateId,
    payloadJson,
    event.schemaVersion,
  ];

  logger.debug(`${LOG_SCOPE}.insertActivityEvent - insert activity_events`, {
    sql: sqlEvent.replace(/\s+/g, " ").trim(),
    params: paramsEvent,
  });
  await conn.query(sqlEvent, paramsEvent);
}

/**
 * Insert actor rows for a given event into activity_event_actors.
 * -This method can run in transaction. For that, it gets the connection as parameter.
 * -This method executes a single statement that inserts several rows into the actors table.
*/
export async function insertActivityEventActors(
  conn: MySqlConnection,
  input: AddActivityEventActorsInput
): Promise<void> {
  if (input.actors.length === 0) return;

  const valuesPlaceholders = input.actors.map(() => "(?, ?, ?, ?)").join(", ");
  const sqlActor = `
    INSERT INTO activity_event_actors (
      event_id,
      actor_type,
      actor_id,
      actor_name
    )
    VALUES ${valuesPlaceholders}
  `;

  const paramsActor = input.actors.flatMap((actor) => [
    input.eventId,
    actor.actorType,
    actor.actorId,
    actor.actorName,
  ]);

  logger.debug(`${LOG_SCOPE}.insertActivityEventActors - insert activity_event_actors`, {
    sql: sqlActor.replace(/\s+/g, " ").trim(),
    params: paramsActor,
  });

  await conn.query(sqlActor, paramsActor);
}


/**
 * Fetch activity events after the last cursor for a given domain/stream/topic.
 * Ordered ascending by sequence_no for stable incremental processing.
 *
 * - `domain` is the activity domain/stream/topic identifier (stored in `activity_events.event_domain`).
 * - This repository intentionally returns **all event_types** for the given domain/stream/topic.
 *   The consumer (projection worker) is responsible for filtering the returned events
 *   by the specific `event_type` values it cares about.
 *
 * Intended for projection workers that consume the shared activity log.
 */
export async function getActivityEventsAfterSequence(
  domain: string, // domain/stream/topic identifier
  lastSequenceNo: number | null,
  limit: number
): Promise<ActivityEventItem[]> {

  if (limit <= 0) return [];
  
  const eventDomain = domain;
  const effectiveLastSequenceNo = lastSequenceNo ?? 0;

  const [rows] = await mysqlPool.query(
    `SELECT sequence_no, event_id, event_occurred_at, event_domain, event_type, aggregate_type, aggregate_id, event_payload_json
     FROM activity_events
     WHERE event_domain = ?
       AND sequence_no > ?
     ORDER BY sequence_no ASC
     LIMIT ?`,
    [eventDomain, effectiveLastSequenceNo, limit]
  );

  const list = (rows as Record<string, unknown>[]) ?? [];
  return list.map((r) => ({
    sequence_no: Number(r.sequence_no ?? 0),
    event_id: String(r.event_id ?? ""),
    event_occurred_at: r.event_occurred_at instanceof Date
        ? r.event_occurred_at
        : new Date(String(r.event_occurred_at)),
    event_domain: String(r.event_domain ?? ""),
    event_type: String(r.event_type ?? ""),
    aggregate_type: String(r.aggregate_type ?? ""),
    aggregate_id: String(r.aggregate_id ?? ""),
    // MySQL JSON may come back as string or as a parsed object depending on the driver.
    // We normalize to a string to keep the worker/projection code predictable.
    event_payload_json: typeof r.event_payload_json === "string"
    ? r.event_payload_json
    : JSON.stringify(r.event_payload_json ?? null),
  }));
}




export async function getActorsForEventIds(
  eventIds: string[]
): Promise<ActivityEventActorItem[]> {
  
  if (eventIds.length === 0) return [];
  
  const uniqueEventIds = [...new Set(eventIds)];
  if (uniqueEventIds.length === 0) return [];

  const placeholders = uniqueEventIds.map(() => "?").join(", ");
  const [rows] = await mysqlPool.query(
    `SELECT event_id, actor_type, actor_id, actor_name
     FROM activity_event_actors
     WHERE event_id IN (${placeholders})
     ORDER BY event_id ASC, actor_type ASC, actor_id ASC`,
    uniqueEventIds
  );

  const list = (rows as Record<string, unknown>[]) ?? [];

  return list.map((r) => ({
    event_id: String(r.event_id ?? ""),
    actor_type: String(r.actor_type ?? ""),
    actor_id: String(r.actor_id ?? ""),
    actor_name: String(r.actor_name ?? ""),
  }));
}
